### ISSUE TITLE
FSD server

### ISSUE THREAD

**Issue by pikachu1992** [kuroneko/fsd#1]
hello i have a old server with this system if you want use my server for tests contact me

best regards

**Comment by donggua2096** [comment]
Can you show me how to install FSD server，

**Comment by pikachu1992** [comment]
https://studentweb.uvic.ca/~norrisng/fsd-doc/

**Comment by donggua2096** [comment]
Hello, I want to build a private FSD continuous flight server, but the server I have built can only be connected by P3D, and X-Plane 11 cannot be connected. Can you help me? The attachment is the source code of FSD server continuous flight server. Thank you very much. I wish you a happy life

**Comment by pikachu1992** [comment]
this server works with both simulators. You are probably using a client
that is not compatible, I suggest that you use the older software
particularly from VATSIM, which allows you to switch the server to your
server. If you are using the server at localhost you have to make sure that
you have all the router ports that the server and the client use open.
I leave here a linl that can help you,
https://studentweb.uvic.ca/~norrisng/fsd-doc/

A sexta, 7/08/2020, 21:20, donggua2096 <notifications@github.com> escreveu:

**Comment by donggua2096** [comment]
Can you send me this download more difficult, my email 2096155326@qq.com

**Comment by pikachu1992** [comment]
I cant sorry. Follow the FSD documentation.Enviado a partir do meu smartphone Samsung Galaxy.
-------- Mensagem original --------De : donggua2096 <notifications@github.com> Data: 07/08/20  22:09  (GMT+00:00) Para: kuroneko/fsd <fsd@noreply.github.com> Cc: pikachu1992 <tmavicente@gmail.com>, Author <author@noreply.github.com> Assunto: Re: [kuroneko/fsd] FSD server (#1) 
Can you send me this download more difficult, my email 2096155326@qq.com

**Comment by donggua2096** [comment]
Can give a URL to touch

**Comment by pikachu1992** [comment]
https://studentweb.uvic.ca/~norrisng/fsd-doc/

**Comment by donggua2096** [comment]
I mean the download of VATSIM's client

**Comment by donggua2096** [comment]
What if I want the password of FSD server to store the information of TXT document and connect to MySQL database?

**Comment by pikachu1992** [comment]
When you have fsdbase running is automatic and you have to store ever in
sql.

A quarta, 23/09/2020, 05:08, donggua2096 <notifications@github.com>
escreveu:

**Comment by donggua2096** [comment]
What is fsdbase

**Comment by donggua2096** [comment]
Is it fsdbase CMS?

**Comment by ghost** [comment]
notice
the link invaild now

**Comment by pikachu1992** [comment]
[https://fsd-doc.norrisng.ca/site/index.html](https://fsd-doc.norrisng.ca/site/index.html)

**Comment by dextercai** [comment]
If you have read the code of FSD, which is also called as fsdbase in some files, you will notice the fsd project has started since 2000s. It used non-modern C++ specification judging from today. I am not good at C language, so I have no idea about implementing the MySQL features in pure C/C++ (It may be hard to work with SQL without LINQ).
Combining with script language (eg. lua) will be better according to my experience. The work will be much easier  for both further development and debug.

**Comment by dextercai** [comment]
> What if I want the password of FSD server to store the information of TXT document and connect to MySQL database?

If you have read the code of FSD, which is also called as fsdbase in some files, you will notice the fsd project has started since 2000s. It used non-modern C++ specification judging from today. I am not good at C language, so I have no idea about implementing the MySQL features in pure C/C++ (It may be hard to work with SQL without LINQ, I guess).
Combining with script language (eg. lua) will be better according to my experience. The work will be much easier for both further development and debug.

**Comment by pikachu1992** [comment]
I started this project and I intend to make some improvements, I put a more sustainable webinterface base and it seems that it is minimally working.

https://vatcon.flyatlantic-va.com/

**Comment by donggua2096** [comment]
Okay, so I'm really looking at how do I store user usage in the form of a database




生活
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kuroneko/fsd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月4日(星期天) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kuroneko/fsd] FSD server (#1)





 
I started this project and I intend to make some improvements, I put a more sustainable webinterface base and it seems that it is minimally working.

**Comment by ghost** [comment]
Can anyone help me see my pull request #4 ......

**Comment by ghost** [comment]
p.s. 这里有国人吗

**Comment by donggua2096** [comment]
有

&nbsp;


生活
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kuroneko/fsd] FSD server (#1)





 
p.s. 这里有国人吗

**Comment by pikachu1992** [comment]
#gamecss 

See the server I sent you, I can say that it works with a Mongo Database instead of Mysql, it is very stable in data issues however the server itself is the same as in this repo. If you want to use the server I sent for your purpose, I am available to help you.

The code for this server is not yet available in Git for the simple fact that I still have to pass some keys to environment variables and I still don't have any developer interested in the project, however the future of this server is to be completely open-source and I hope to be able to have a team for a good development of this system.

https://vatcon.flyatlantic-va.com/

**Comment by pikachu1992** [comment]
See the server I sent you, I can say that it works with a Mongo Database instead of Mysql, it is very stable in data issues however the server itself is the same as in this repo. If you want to use the server I sent for your purpose, I am available to help you.

The code for this server is not yet available in Git for the simple fact that I still have to pass some keys to environment variables and I still don't have any developer interested in the project, however the future of this server is to be completely open-source and I hope to be able to have a team for a good development of this system.

https://vatcon.flyatlantic-va.com/

**Comment by donggua2096** [comment]
At present, I am interested in this project. I will rewrite this project with my understanding. At this time, I will use MySQL as the library for storing accounts


生活
***@***.***





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "kuroneko/fsd"                                                                                    ***@***.***>;
发送时间: 2021年7月17日(星期六) 凌晨2:18
收件人: ***@***.***>;
抄送: ***@***.******@***.***>;
主题: Re: [kuroneko/fsd] FSD server (#1)



See the server I sent you, I can say that it works with a Mongo Database instead of Mysql, it is very stable in data issues however the server itself is the same as in this repo. If you want to use the server I sent for your purpose, I am available to help you.
The code for this server is not yet available in Git for the simple fact that I still have to pass some keys to environment variables and I still don't have any developer interested in the project, however the future of this server is to be completely open-source and I hope to be able to have a team for a good development of this system.
https://vatcon.flyatlantic-va.com/

**Comment by ghost** [comment]
> At present, I am interested in this project. I will rewrite this project with my understanding. At this time, I will use MySQL as the library for storing accounts 生活 ***@***.***
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "kuroneko/fsd" ***@***.***>; 发送时间: 2021年7月17日(星期六) 凌晨2:18 收件人: ***@***.***>; 抄送: ***@***.******@***.***>; 主题: Re: [kuroneko/fsd] FSD server (#1) See the server I sent you, I can say that it works with a Mongo Database instead of Mysql, it is very stable in data issues however the server itself is the same as in this repo. If you want to use the server I sent for your purpose, I am available to help you. The code for this server is not yet available in Git for the simple fact that I still have to pass some keys to environment variables and I still don't have any developer interested in the project, however the future of this server is to be completely open-source and I hope to be able to have a team for a good development of this system. https://vatcon.flyatlantic-va.com/ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.拑

你写出来了我第一个用

**Comment by donggua2096** [comment]
因为一些特殊原因，我的项目将不会开源



发自我的iPhone


------------------ Original ------------------
From: gamecss ***@***.***&gt;
Date: Fri,Jul 23,2021 7:31 PM
To: kuroneko/fsd ***@***.***&gt;
Cc: donggua2096 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [kuroneko/fsd] FSD server (#1)





  
At present, I am interested in this project. I will rewrite this project with my understanding. At this time, I will use MySQL as the library for storing accounts 生活 @.***
 …
 ------------------ 原始邮件 ------------------ 发件人: "kuroneko/fsd" @.&gt;; 发送时间: 2021年7月17日(星期六) 凌晨2:18 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [kuroneko/fsd] FSD server (#1) See the server I sent you, I can say that it works with a Mongo Database instead of Mysql, it is very stable in data issues however the server itself is the same as in this repo. If you want to use the server I sent for your purpose, I am available to help you. The code for this server is not yet available in Git for the simple fact that I still have to pass some keys to environment variables and I still don't have any developer interested in the project, however the future of this server is to be completely open-source and I hope to be able to have a team for a good development of this system. https://vatcon.flyatlantic-va.com/ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.拑
  
你写出来了我第一个用

**Comment by ghost** [comment]
悲




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kuroneko/fsd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月24日(星期六) 凌晨4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kuroneko/fsd] FSD server (#1)





 因为一些特殊原因，我的项目将不会开源 
 
 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------ 
 From: gamecss ***@***.***&amp;gt; 
 Date: Fri,Jul 23,2021 7:31 PM 
 To: kuroneko/fsd ***@***.***&amp;gt; 
 Cc: donggua2096 ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 Subject: Re: [kuroneko/fsd] FSD server (#1) 
 
 
 
 
 
    
 At present, I am interested in this project. I will rewrite this project with my understanding. At this time, I will use MySQL as the library for storing accounts 生活 @.*** 
  … 
  ------------------ 原始邮件 ------------------ 发件人: "kuroneko/fsd" @.&amp;gt;; 发送时间: 2021年7月17日(星期六) 凌晨2:18 收件人: @.&amp;gt;; 抄送: @.@.&amp;gt;; 主题: Re: [kuroneko/fsd] FSD server (#1) See the server I sent you, I can say that it works with a Mongo Database instead of Mysql, it is very stable in data issues however the server itself is the same as in this repo. If you want to use the server I sent for your purpose, I am available to help you. The code for this server is not yet available in Git for the simple fact that I still have to pass some keys to environment variables and I still don't have any developer interested in the project, however the future of this server is to be completely open-source and I hope to be able to have a team for a good development of this system. https://vatcon.flyatlantic-va.com/ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.拑 
    
 你写出来了我第一个用

**Comment by ogb912** [comment]
I have a project of whole flight simulator platform. It's base Sring Boot. If anyone have interesting，please contact me. The code is on the Aliyun devops platfrom

**Comment by pikachu1992** [comment]
i'm interested

**Comment by ogb912** [comment]
I copied the code to github. If you have interesting the code, you can view this page [https://github.com/ogb912/fsd_SpringBoot](url)

**Comment by ogb912** [comment]
the first problem is how to storage the FSD user into the database not the cert.txt file in the Java,

**Comment by dextercai** [comment]
As you see, the cert file can be regarded as a special database without any data compression and optimization. And the auth process is not very hard to understand. An interface or virtual class providing the `checkPassword(username, password)` function can basically meet the needs. 

As for the specific implementation, it depends on your actual structure. RPC, WebAPI, MySQL or other database. It is up to you. 

 BTW, I rewritten the fsd about 3 yrs ago which called as Rum. the source code was protected by NDA. But the structure of the system can be discussed, if some one is interested.

**Comment by ogb912** [comment]
其实我用Java，Spring Boot的初衷不光是用户存储的问题，我其实是想搭建一个基于Spring Boot的前后端分离的模拟飞行平台，后端可以提供所有的接口，前端就可以直接调用，这样做可以更轻量化。
In fact, I use Java and Spring want to build a flight simulator platform according front-end rear-end separation

**Comment by dextercai** [comment]
This is also the design idea of my software. Separation of protocol and control. Using microservice architecture.

**Comment by ogb912** [comment]
VATSIM's fsd server is a special edition，but VATSIM’s fsd server is a closed software. We didn't know how to work

**Comment by pikachu1992** [comment]
the vatsim code is in fact a different version of the FSD, however the protocol is exactly the same with a few more things that are irrelevant to the main need which is to connect two simulators in a network.

**Comment by pikachu1992** [comment]
I have some code made by me that can establish a server where it is possible to connect users with Euroscope and vPilot, however all this code is written in python and my interest would be to continue this code changing the protocol to a different protocol and develop their clients. If anyone is interested in moving this forward in python I have extensive knowledge of the entire FSD protocol with my eyes closed.

**Comment by ogb912** [comment]
Is this your say the fsd code
 [xivap-fsd-server](https://github.com/pikachu1992/xivap-fsd-server)

**Comment by pikachu1992** [comment]
no, this is a fork by another author and not mine. I mostly gather my projects in GitLab for some time, which means that the existing projects on my GitHub are out of use or are just for consultation.

When I say that I have code written the way I mentioned it does not mean that it is public for obvious reasons, however it has always been and will be my vision to follow the open source path and not another, but this will only be done when I find a team of interested developers in starting an open source project and there I will make available all the information I gathered over these years of development on this subject.

It is my goal to start, advance and build a project desired by many in a joint community and not offer a code fork written, thought and architected for years, a new network with exclusive and non-inclusive ideologies as we already have the examples of the existing ones.

It makes no sense to create a new network if it does not solve the current problems of the existing ones, that will be the only way that customers will have to choose theirs and not another and with that in mind it is my responsibility to ensure that the code I write serves the a goal common to the entire disaffected community and not just to satisfy a personal desire.

I will always be interested if it is to develop for a community, in an open source way and guaranteeing a free service to all users of the network, since for all of us, aviation is a hobby and not a source of income.

With this I did not say or say that your objective will be one of the ones I mentioned, I am just justifying the fact that I can't find what you want in my repository.

**Comment by ogb912** [comment]
If we can't change the source code from txt to database, how can we sync the cert.txt file and database

**Comment by ghost** [comment]
I finished make fsd to read cert from SQLite3 database.
See them:
[commit 739b3f6fa2b9ad3fdfc0b766d71504fd5a5403fe of cfcsim/fsd](https://github.com/cfcsim/fsd/commit/739b3f6fa2b9ad3fdfc0b766d71504fd5a5403fe)
[commit 2a96e0a0c1b0699bd59b31f632f739ad75095642 of cfcsim/fsd](https://github.com/cfcsim/fsd/commit/2a96e0a0c1b0699bd59b31f632f739ad75095642)
** You must apply commit 739b3f6fa2b9ad3fdfc0b766d71504fd5a5403fe first and apply commit 2a96e0a0c1b0699bd59b31f632f739ad75095642.

**Comment by ghost** [comment]
there is an easy convert script in python:
```python3
import sqlie3
cert_group = []
with open('cert.txt', 'r') as f:
    text = f.read()
    if text.startswith(';'):
        continue
    cert = text.split()
    if not len(cert) == 3:
        raise RuntimeError('Error line: '+text)
    cert_group.append(tuple(cert))
cursor = sqlite3.connect('cert.sqlitedb').cursor()
cursor.executemany('INSERT INTO cert VALUES (?, ?, ?);', cert_group)
cursor.connection.commit()
cursor.connection.close()
```

**Comment by dextercai** [comment]
> If we can't change the source code from txt to database, how can we sync the cert.txt file and database

There is a lot of way to change cert.txt into a database, if you are using java. Just like the website project. So, I said a lot. The original intention is to forget FSD. Only FSD protocol needs reference. If you use languages other than C, everything is flexible.

If you just want to create a cert.txt with database (one-way sync), just feel free to use a java.io.writer with any database middleware, that is enough.

**Comment by michael-filhol** [comment]
Hello,
I am discovering this thread and wondering if interest has spawned to evolve this rather old code, in any way that should be coordinated.
I am the developer of ATC-pie, an ATC simulation program that is able to connect, among other session types, to plain FSD servers like this one (by "plain" I mean non-VATSIM, i.e. without their later-added hidden parts in the protocol). As Euroscope had discontinued the support for plain FSD, I added this feature for groups to be able to fly multi-player with ATC. I know at least one flight club that has now been using it for three years, and I believe it is even the only solution outside of world-wide networks.
So if this protocol is about to be altered, I would like to be aware of it, and maybe we could coordinate the changes, why not even take the opportunity to address its limitations in terms of ATC interaction.

**Comment by pikachu1992** [comment]
We can talk more about the topic even though this project is just a fork of an open source FSD project. However, I am available to listen to your idea better.

**Comment by ghost** [comment]
what a hot issue

**Comment by michael-filhol** [comment]
So to clarify, is anybody currently working on extending the code (and keeping it GPL)?

As I said in a brief subsequent exchange with kuroneko, the good thing to me about this protocol is that everybody can now connect to it through SWIFT, regardless of their actual sim program... and it is the only way unless you go world-wide group on VATSIM, then have to follow their rules. So I think it could have a future if better known as an option, and updated to support a few things currently blocking realistic ATC interaction—it has now indeed aged quite a bit.

**Comment by ghost** [comment]
> So to clarify, is anybody currently working on extending the code (and keeping it GPL)?
> 
> As I said in a brief subsequent exchange with kuroneko, the good thing to me about this protocol is that everybody can now connect to it through SWIFT, regardless of their actual sim program... and it is the only way unless you go world-wide group on VATSIM, then have to follow their rules. So I think it could have a future if better known as an option, and updated to support a few things currently blocking realistic ATC interaction—it has now indeed aged quite a bit.

I used to working in it... as cfcsim/fsd
But now I prefer LinkTechTips/BetterFSD-Java
